language: node_js
node_js:
- '9'
cache: yarn
services:
- postgresql
before_script:
- psql -c 'create database hbtest;' -U postgres
- npm run db:migrate
after_success:
- coveralls < coverage/lcov.info
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: evQ0osgrYrIScdP23H27HPjtaIkblixC9jv9VYGXaUCfdreZEjCNlG/i8hvBx5UIR8hCdxpS//WKpubZEHQhlxaDHUjxNJeZdj/HPF7GJsHOiRyIA4O9urtoumGH0Qtxf/FUJCs85yCLI+4d9act+g2vWTRi913dejnrMXtYo5GeAolFjhWj45ae2AVw8bgmvo8kifQpdL/cSQ59Nz1eu8gWzTp4Z3hfaM8YHFHR6JlMbb+LGXHo+3k5l5sxWbBcH2sWkplUjQJFfM51l5h/Ma3N07ZjdiXUkyuuWcCIj/yjkK3JG0T+jtNo8EFRQr3KYQQIDQirjFAhih6MMfFCRMlfHAH+UwUWiMR2GVJLvtoAVLlPYi9E0pLAG03hbTpb3ZcCUu3A2lhMzkO6xgP1TYa1fLdqZQCQ+U3jp2ntsc5ZB8g6FO+qEfnA7yNsvg1xd33SfT3cpgg7hUcFZ/K1RJi6rty3/qdwM5/kHdxpOxqgKPJeUSz6Z5bK4T+p7lZVFHoZrUjI16Q+5ULvLMdHKsUwXCr9becpjMLWJQX0FY588SWGswJdn1UdWgCM3WnrhwmgyHyo1f8j+y4r4eXr9snYPlvGrhaCh6MdC8R6z+uyYkTJMvTE8sqqFs/WPRng7F8M9ja4DB1o1xmqHftgzsKOeoL4lUVpPDDzcYe1l0E=
  app: habit-tracker-server
  run:
    - "npm run db:migrate"
  on:
    repo: PeerProg/habit-tracker-server
    branch: develop
