language: node_js
node_js: 'stable'

services:
  - postgresql

before_script:
  - psql -c 'create database hbtest;' -U postgres
  - npm run migratedb

after_success:
  - coveralls < coverage/lcov.info
