language: node_js
node_js:
- '9'
cache: yarn
services:
- postgresql
before_script:
- psql -c 'create database hbtest;' -U postgres
- npm run db:migrate
after_success:
- coveralls < coverage/lcov.info
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: qbrZgQ6utDyg+Aq53srwq3p7SmYLlh3E8WyUAj25XVKrolIfT1YCTYwPaHC1GhSrufC/i/4vaOYxLikTFCLBFOEtVxm2FQCpBqhm6ZcU/TcFQAts67LMG2bVQg2kZ0XyyJrlklcgY7+hwN0Nb3pK5XcVNInJxh8R6IuNdYvy1iQuXCEs+7IzxSDJcsUThQdcAwVyn+dSIdQ+iy9/60qmLG+dPg+Ivdh1wsq4juGJbhc0LlGWfyS8co7q2QyoCumNR0r5a8uApMEwCU0pJAsTj9cuaUV7iA66TLGCIOF2dBR6FUqUakY1uIV6ZDPd/GMCLFNX8n1HdmY/OeuCcA4tBNeXwyEFrpk4Hva+gY9U6KTfHUS1jtZkdgFJWnvF0Z93T+Uy+sXCq7SKbwn0qYGca5OubfNa/PWaJ9ULTRzUENKePDBsYDBr0JRLLtn611irJy29EMSZh4CdA+jNWA/yCAfpICP9P9jffg0sSI6JLz94oxpoGHzp1m1MPaGNM39UnJe9BkhNoOM+FK8sPTXE4IVdx62Y8B2w5W4N+o/JAJVE7AA/FxZHkIBhpvWmnmtSoShrFmoHb5Jdn73pUxugeiAAOKVv3FwtW+R8tXwbmAPPMzt93n1tqdCvORUd6PmMe+LxJissiNn3gMND3PlQVu+dOfZNjehDWlNkTtelc9E=
  app: habit-tracker-server
  on:
    repo: PeerProg/habit-tracker-server
    branch: develop
  run:
    - npm run db:migrate
