language: node_js

node_js:
  - '9'

cache: yarn

services:
  - postgresql

before_script:
  - psql -c 'create database hbtest;' -U postgres
  - npm run db:migrate

after_success:
  - coveralls < coverage/lcov.info
